# simplified haskell-ci Travis setup
# see also https://github.com/haskell-CI/haskell-ci
language: haskell

cache:
  directories:
    - $HOME/.cabal/store

cabal: "2.4"
  - "8.6.3"
  - "8.4.4"
  - "8.2.2"
  - "8.0.2"
  - "7.10.3"
  - "7.8.4"
  - "7.6.3"
  - "7.4.2"

install:
 - cabal --version
 - ghc --version

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - cabal v2-update
 - cabal v2-build --dep all
#- cabal check
 - cabal v2-sdist
  
# prepare `cabal sdist` source-tree environment to make sure source-tarballs are complete
 - cabal v2-sdist
 - cd dist-newstyle/sdists/
 - for TAR in ./*-*.tar.gz; do tar -xf $TAR; mv -v $TAR $(echo "$TAR" | sed 's/-[0-9.]*.tar.gz$//'); done

 # first build just hackage-security with installed constraints, with and without tests.
 # silly yaml, seeing : colon
 - "echo packages: ./hackage-security > cabal.project"
 - cabal v2-build --disable-tests --constraint "directory installed" --constraint "bytestring installed" all
 - cabal v2-test  --enable-tests  --constraint "directory installed" --constraint "bytestring installed" all

 # build all packages and run testsuite
 - cp -v ../cabal.project ./
 - cabal v2-build -j1 all
 - cabal v2-test  -j1 all
 
# EOF
